### ISSUE TITLE
ERROR: No matching distribution found for pyvirtualcam

### ISSUE THREAD

**Issue by michaelschung** [letmaik/pyvirtualcam#116] opened 2024-01-31 18:27 UTC
- Operating system: MacOS Sonoma 14.1.1
- Python version: 3.11.7
- pyvirtualcam version: 0.11.0
- Virtual camera (OBS, v4l2loopback, UnityCapture):  OBS
- Virtual camera version:

`pip3 install pyvirtualcam` gives me the following error:

```
ERROR: Could not find a version that satisfies the requirement pyvirtualcam (from versions: none)
ERROR: No matching distribution found for pyvirtualcam
```

The same happens if I try to use the PyCharm package installer. Would greatly appreciate help!
...

**To Reproduce**
```bash
pip3 install pyvirtualcam
```

**Comment by letmaik** [comment] 2024-02-08 20:28
Duplicate of #97.

**Closed by letmaik** 2024-02-08 20:28 UTC
